-- RSAL P7.3d checkpoint full backup
-- checkpoint: P7.3d_forecast_v1_1_confidence_gate_stable
-- generated by scripts/export_p7_checkpoint.py

CREATE SCHEMA IF NOT EXISTS ccc;

-- ============================================================
-- Functions
-- ============================================================

-- Function: ccc.forecast_confidence_gate_v1(double precision,double precision,double precision)
CREATE OR REPLACE FUNCTION ccc.forecast_confidence_gate_v1(p_resonance double precision, p_friction double precision, p_neutral double precision)
 RETURNS jsonb
 LANGUAGE plpgsql
 IMMUTABLE
AS $function$
DECLARE
  v_resonance double precision := GREATEST(0.0, COALESCE(p_resonance, 0.0));
  v_friction  double precision := GREATEST(0.0, COALESCE(p_friction, 0.0));
  v_neutral   double precision := GREATEST(0.0, COALESCE(p_neutral, 0.0));

  v_total_force double precision := 0.0;
  v_evidence_score double precision := 0.0;
  v_direction_balance double precision := 0.0;
  v_confidence double precision := 0.50;
BEGIN
  v_total_force := v_resonance + v_friction + v_neutral;

  IF v_total_force <= 0 THEN
    v_evidence_score := 0.0;
    v_direction_balance := 0.0;
    v_confidence := 0.50;
  ELSE
    -- 证据量门控：total_force >= 1.0 视为证据量充足
    v_evidence_score := LEAST(1.0, v_total_force / 1.0);

    -- 方向平衡：
    -- resonance 推高 A 面置信
    -- friction 压低 A 面置信
    -- neutral 只轻微扣分，避免中性噪音过度惩罚
    v_direction_balance :=
      (v_resonance - v_friction - v_neutral * 0.20) / v_total_force;

    v_confidence := LEAST(0.95, GREATEST(0.30,
      0.50 + v_direction_balance * v_evidence_score * 0.35
    ));
  END IF;

  RETURN jsonb_build_object(
    'confidence',        round(v_confidence::numeric, 4),
    'total_force',       round(v_total_force::numeric, 4),
    'evidence_score',    round(v_evidence_score::numeric, 4),
    'direction_balance', round(v_direction_balance::numeric, 4),
    'model',             'confidence_evidence_gate_v1',
    'formula',           '0.50 + direction_balance * evidence_score * 0.35'
  );
END;
$function$
;

-- Function: ccc.forecast_v1_1_core(text)
CREATE OR REPLACE FUNCTION ccc.forecast_v1_1_core(p_entity_name text)
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE
AS $function$
DECLARE
  v_keywords_a text[] := ARRAY[
    '监管','打压','审查','维稳','资本管制','收紧','收缩','清洗','反腐','国家安全','外部势力','军事演习','统一','制裁','管控','严打','斗争',
    '監管','打壓','審查','維穩','資本管制','收緊','收縮','清洗','反腐','國家安全','外部勢力','軍事演習','統一','制裁','管控','嚴打','鬥爭',
    'crackdown','tightening','control','regulation','censorship','security','purge','anti-corruption','military drill','sanction','national security','containment',
    '規制','弾圧','検閲','統制','安全保障','粛清','反腐敗','軍事演習','制裁','管理強化','台湾有事','対中強硬',
    'jianguan','daji','shencha','weiwen','shoujin','shousuo','qingxi','fanfu','guankong','guoan','junshiyanxi','zhicai'
  ];

  v_keywords_b text[] := ARRAY[
    '开放','放宽','改革','市场化','民营','松绑','宽松','刺激','减税','外资','营商环境','合作','谈判','缓和',
    '開放','放寬','改革','市場化','民營','鬆綁','寬鬆','刺激','減稅','外資','營商環境','合作','談判','緩和',
    'opening','liberalization','reform','marketization','private sector','easing','stimulus','tax cut','foreign investment','cooperation','negotiation','de-escalation',
    '開放','緩和','改革','自由化','市場化','民営化','金融緩和','刺激策','減税','外資誘致','協力','交渉','対話','関係改善',
    'kaifang','fangkuan','gaige','shichanghua','minying','songbang','kuansong','ciji','jianshui','waizi','hezuo','tanpan','huanhe'
  ];

  v_profile jsonb := '{}'::jsonb;
  v_trajectory jsonb := '{}'::jsonb;
  v_signals jsonb := '[]'::jsonb;
  v_contradictions jsonb := '[]'::jsonb;
  v_behaviors jsonb := '[]'::jsonb;
  v_timeline jsonb := '[]'::jsonb;
  v_alignment jsonb := '[]'::jsonb;

  v_entity_id bigint;
  v_profile_id bigint;
  v_route_profile text := 'neutral_agent';

  v_pressure float := 0.5;
  v_trend text := 'stable';
  v_forecast_a text := '强化现有路线';
  v_forecast_b text := '路线调整';
  v_prob_a float := 0.55;
  v_prob_b float := 0.45;

  v_resonance float := 0;
  v_friction float := 0;
  v_neutral float := 0;
  v_total_force float := 0;
  v_confidence float := 0.5;
BEGIN
  SELECT ep.id, ep.entity_id,
         jsonb_build_object(
           'essence', ep.essence,
           'survival_mode', ep.survival_mode,
           'mirror_bias', ep.mirror_bias,
           'core_drives', ep.core_drives,
           'behavior_pattern', ep.behavior_pattern,
           'confidence', ep.confidence
         )
  INTO v_profile_id, v_entity_id, v_profile
  FROM ccc.entity_profiles ep
  WHERE lower(ep.entity_name) = lower(p_entity_name)
  LIMIT 1;

  IF v_profile_id IS NULL THEN
    RETURN jsonb_build_object(
      'ok', false,
      'error', 'entity profile not found',
      'entity', p_entity_name
    );
  END IF;

  SELECT jsonb_build_object(
           'pressure', et.pressure,
           'pressure_trend', et.pressure_trend,
           'trajectory_status', et.trajectory_status,
           'risk_level', et.risk_level,
           'key_drivers', et.key_drivers,
           'supporting_signals', et.supporting_signals,
           'next_possible_events', et.next_possible_events,
           'prediction', et.short_term_prediction,
           'prediction_horizon', et.prediction_horizon,
           'confidence', et.confidence
         )
  INTO v_trajectory
  FROM ccc.entity_trajectories et
  WHERE et.entity_profile_id = v_profile_id
  ORDER BY et.snapshot_date DESC
  LIMIT 1;

  v_pressure := COALESCE((v_trajectory->>'pressure')::float, 0.5);
  v_trend := COALESCE(v_trajectory->>'pressure_trend', 'stable');

  -- P7.3b route_profile mapping
  v_route_profile := CASE
    WHEN v_profile->>'survival_mode' IN ('权力集中化', '政权延续', '地缘安全扩张')
      THEN 'authoritarian'
    WHEN v_profile->>'survival_mode' IN ('交易利益最大化', '重新定价与秩序解构')
      THEN 'transactional'
    WHEN v_profile->>'survival_mode' IN ('流动性管理', '美元体系稳定管理')
      THEN 'financial'
    WHEN v_profile->>'survival_mode' IN ('议程设定', '精英治理议程设定')
      THEN 'governance'
    ELSE 'neutral_agent'
  END;

  SELECT COALESCE(jsonb_agg(x.obj ORDER BY x.strength DESC), '[]'::jsonb)
  INTO v_signals
  FROM (
    SELECT
      s.strength,
      jsonb_build_object(
        'type', s.signal_type,
        'text', s.signal_text,
        'strength', s.strength,
        'trigger_condition', s.trigger_condition,
        'linked_prediction', s.linked_prediction,
        'source', s.source_label
      ) AS obj
    FROM ccc.signals s
    WHERE s.entity_profile_id = v_profile_id
      AND s.is_active = true
    ORDER BY s.strength DESC
    LIMIT 5
  ) x;

  SELECT COALESCE(jsonb_agg(x.obj ORDER BY x.gap DESC), '[]'::jsonb)
  INTO v_contradictions
  FROM (
    SELECT
      ce.narrative_gap AS gap,
      jsonb_build_object(
        'official', ce.official_narrative,
        'counter_signals', ce.counter_signals,
        'real_indicators', ce.real_indicators,
        'gap', ce.narrative_gap,
        'severity', ce.severity,
        'confidence_decay', ce.confidence_decay,
        'source_labels', ce.source_labels,
        'trust_levels', ce.trust_levels
      ) AS obj
    FROM ccc.contradiction_engine ce
    WHERE ce.entity_id = v_entity_id
      AND ce.is_active = true
    ORDER BY ce.narrative_gap DESC
    LIMIT 5
  ) x;

  SELECT COALESCE(jsonb_agg(x.obj ORDER BY x.confidence DESC), '[]'::jsonb)
  INTO v_behaviors
  FROM (
    SELECT
      bm.confidence,
      jsonb_build_object(
        'prediction', bm.predicted_action,
        'type', bm.action_type,
        'confidence', bm.confidence,
        'historical_accuracy', bm.historical_accuracy,
        'horizon', bm.time_horizon,
        'triggers', bm.trigger_conditions,
        'counter_signals', bm.counter_signals
      ) AS obj
    FROM ccc.behavioral_models bm
    WHERE bm.entity_profile_id = v_profile_id
    ORDER BY bm.confidence DESC
    LIMIT 3
  ) x;

  SELECT COALESCE(jsonb_agg(x.obj ORDER BY x.event_time), '[]'::jsonb)
  INTO v_timeline
  FROM (
    SELECT
      en.event_time,
      jsonb_build_object(
        'time', en.event_time,
        'sequence_order', en.sequence_order,
        'essence', en.essence,
        'mechanism', en.mechanism,
        'pressure', en.pressure,
        'signal_strength', en.signal_strength,
        'causal_weight', en.causal_weight,
        'escalation_score', en.escalation_score
      ) AS obj
    FROM ccc.event_nodes en
    JOIN ccc.event_chains ec ON ec.id = en.chain_id
    WHERE ec.entity_id = v_entity_id
    ORDER BY en.event_time DESC
    LIMIT 5
  ) x;

  v_prob_a := CASE
    WHEN v_pressure >= 0.8 AND v_trend = 'rising' THEN 0.78
    WHEN v_pressure >= 0.7 AND v_trend = 'rising' THEN 0.68
    WHEN v_pressure >= 0.6 AND v_trend = 'stable' THEN 0.58
    WHEN v_pressure >= 0.5 AND v_trend = 'declining' THEN 0.45
    ELSE 0.55
  END;

  v_prob_b := 1.0 - v_prob_a;

  -- P7.3b option A
  v_forecast_a := CASE v_profile->>'survival_mode'
    WHEN '权力集中化' THEN '权力绝对集中'
    WHEN '地缘安全扩张' THEN '军事行动升级'
    WHEN '交易利益最大化' THEN '单边交易强化'
    WHEN '重新定价与秩序解构' THEN '破坏性极限施压'
    WHEN '政权延续' THEN '刚性社会维稳'
    WHEN '流动性管理' THEN '流动性干预'
    WHEN '美元体系稳定管理' THEN '流动性救市'
    WHEN '议程设定' THEN '治理框架推进'
    WHEN '精英治理议程设定' THEN '全球协调增强 / 精英治理深化'
    ELSE '强化现有路线'
  END;

  -- P7.3b option B
  v_forecast_b := CASE v_profile->>'survival_mode'
    WHEN '权力集中化' THEN '战术性防御退让'
    WHEN '地缘安全扩张' THEN '战略收缩 / 外交谈判'
    WHEN '交易利益最大化' THEN '多边合作'
    WHEN '重新定价与秩序解构' THEN '协议达成与筹码套现'
    WHEN '政权延续' THEN '市场化自救放权'
    WHEN '流动性管理' THEN '货币收紧'
    WHEN '美元体系稳定管理' THEN '纪律性紧缩'
    WHEN '议程设定' THEN '主权让步'
    WHEN '精英治理议程设定' THEN '国家主权反弹 / 逆全球化加深'
    ELSE '路线调整'
  END;

  WITH contradiction_force AS (
    SELECT
      ce.id,
      ce.official_narrative,
      array_to_string(ce.counter_signals, ' ') AS counter_text,
      array_to_string(ce.real_indicators, ' ') AS real_text,
      ce.narrative_gap,
      ce.source_labels,
      ce.trust_levels,

      EXISTS (
        SELECT 1 FROM unnest(v_keywords_a) kw
        WHERE array_to_string(ce.counter_signals, ' ') ILIKE '%' || kw || '%'
           OR array_to_string(ce.real_indicators, ' ') ILIKE '%' || kw || '%'
      ) AS hard_hit_a,

      EXISTS (
        SELECT 1 FROM unnest(v_keywords_b) kw
        WHERE array_to_string(ce.counter_signals, ' ') ILIKE '%' || kw || '%'
           OR array_to_string(ce.real_indicators, ' ') ILIKE '%' || kw || '%'
      ) AS hard_hit_b,

      EXISTS (
        SELECT 1 FROM unnest(v_keywords_a) kw
        WHERE ce.official_narrative ILIKE '%' || kw || '%'
      ) AS official_hit_a,

      EXISTS (
        SELECT 1 FROM unnest(v_keywords_b) kw
        WHERE ce.official_narrative ILIKE '%' || kw || '%'
      ) AS official_hit_b,

      EXISTS (
        SELECT 1 FROM unnest(ce.trust_levels) tl
        WHERE tl = 'T6'
      ) AS has_t6,

      (
        SELECT AVG(
          COALESCE(
            (
              ccc.source_effective_weight(sl.label::text, NULL::text, NULL::text)
              ->'weights'->>'reverse_indicator_weight'
            )::double precision,
            CASE
              WHEN sl.trust_level = 'T6' THEN 0.65
              WHEN sl.trust_level = 'T3' THEN 0.70
              WHEN sl.trust_level = 'T2' THEN 0.60
              ELSE 0.55
            END
          )
          *
          CASE WHEN sl.trust_level = 'T6' THEN 1.10 ELSE 1.00 END
        )
        FROM (
          SELECT
            labels.label,
            COALESCE(levels.trust_level, 'UNK') AS trust_level
          FROM unnest(ce.source_labels) WITH ORDINALITY labels(label, ord)
          LEFT JOIN unnest(ce.trust_levels) WITH ORDINALITY levels(trust_level, ord)
            ON labels.ord = levels.ord
        ) sl
      ) AS p6_weight

    FROM ccc.contradiction_engine ce
    WHERE ce.entity_id = v_entity_id
      AND ce.is_active = true
  ),
  routed AS (
    SELECT
      *,
      CASE
        -- Authoritarian
        WHEN v_route_profile = 'authoritarian'
         AND has_t6
         AND (
           official_narrative ILIKE '%透明通报%'
           OR official_narrative ILIKE '%自然界%'
           OR official_narrative ILIKE '%源于自然%'
           OR official_narrative ILIKE '%开放包容%'
           OR official_narrative ILIKE '%合作共赢%'
           OR official_narrative ILIKE '%和平解决%'
           OR official_narrative ILIKE '%无意动武%'
           OR official_narrative ILIKE '%自由贸易%'
           OR official_narrative ILIKE '%自由贸易秩序%'
           OR official_narrative ILIKE '%重要力量%'
           OR official_narrative ILIKE '%保持稳定%'
           OR official_narrative ILIKE '%稳定复苏%'
           OR official_narrative ILIKE '%改革开放%'
           OR official_narrative ILIKE '%持续深化%'
         )
          THEN 'A'

        WHEN v_route_profile = 'authoritarian'
         AND (
           counter_text ILIKE '%军事演习%' OR real_text ILIKE '%军事演习%'
           OR counter_text ILIKE '%统一时间表%' OR real_text ILIKE '%统一时间表%'
           OR counter_text ILIKE '%样本销毁%' OR real_text ILIKE '%样本销毁%'
           OR counter_text ILIKE '%调查受限%' OR real_text ILIKE '%调查受限%'
           OR counter_text ILIKE '%预警压制%' OR real_text ILIKE '%预警压制%'
           OR counter_text ILIKE '%出口限制%' OR real_text ILIKE '%出口限制%'
           OR counter_text ILIKE '%供应链切断%' OR real_text ILIKE '%供应链切断%'
           OR counter_text ILIKE '%贸易武器化%' OR real_text ILIKE '%贸易武器化%'
           OR counter_text ILIKE '%技术脱钩%' OR real_text ILIKE '%技术脱钩%'
           OR counter_text ILIKE '%关键矿产%' OR real_text ILIKE '%关键矿产%'
           OR counter_text ILIKE '%债务陷阱%' OR real_text ILIKE '%债务陷阱%'
           OR counter_text ILIKE '%经济胁迫%' OR real_text ILIKE '%经济胁迫%'
         )
          THEN 'A'

        -- Governance
        WHEN v_route_profile = 'governance'
         AND (
           official_narrative ILIKE '%全球治理%'
           OR official_narrative ILIKE '%自由贸易%'
           OR official_narrative ILIKE '%服务全人类%'
           OR official_narrative ILIKE '%开放包容%'
           OR official_narrative ILIKE '%利益相关者%'
         )
          THEN 'B'

        -- Financial
        WHEN v_route_profile = 'financial'
         AND (
           real_text ILIKE '%政治施压%'
           OR counter_text ILIKE '%政治施压%'
           OR real_text ILIKE '%听证施压%'
           OR counter_text ILIKE '%听证施压%'
           OR real_text ILIKE '%任命政治化%'
           OR counter_text ILIKE '%任命政治化%'
           OR real_text ILIKE '%政治周期%'
           OR counter_text ILIKE '%政治周期%'
           OR real_text ILIKE '%MMT%'
           OR counter_text ILIKE '%MMT%'
           OR real_text ILIKE '%流动性锁死%'
           OR counter_text ILIKE '%流动性锁死%'
         )
          THEN 'A'

        WHEN v_route_profile = 'financial'
         AND (
           official_narrative ILIKE '%独立%'
           OR official_narrative ILIKE '%基于数据%'
           OR official_narrative ILIKE '%保持稳定%'
           OR official_narrative ILIKE '%符合预期%'
         )
          THEN 'NEUTRAL'

        -- Transactional
        WHEN v_route_profile = 'transactional'
         AND (
           counter_text ILIKE '%技术脱钩%' OR real_text ILIKE '%技术脱钩%'
           OR counter_text ILIKE '%加征关税%' OR real_text ILIKE '%加征关税%'
           OR counter_text ILIKE '%关税%' OR real_text ILIKE '%关税%'
           OR counter_text ILIKE '%极限施压%' OR real_text ILIKE '%极限施压%'
           OR counter_text ILIKE '%供应链重组%' OR real_text ILIKE '%供应链重组%'
           OR counter_text ILIKE '%单边%' OR real_text ILIKE '%单边%'
         )
          THEN 'A'

        WHEN v_route_profile = 'transactional'
         AND (
           official_narrative ILIKE '%极好的协议%'
           OR official_narrative ILIKE '%随时谈判%'
           OR official_narrative ILIKE '%目标有限%'
           OR official_narrative ILIKE '%可以谈判%'
         )
          THEN 'B'

        -- Global residual
        WHEN (
           counter_text ILIKE '%宣战%' OR real_text ILIKE '%宣战%'
           OR counter_text ILIKE '%全面制裁%' OR real_text ILIKE '%全面制裁%'
           OR counter_text ILIKE '%全面戒严%' OR real_text ILIKE '%全面戒严%'
           OR counter_text ILIKE '%切断代理行%' OR real_text ILIKE '%切断代理行%'
        )
          THEN 'A'

        ELSE 'NEUTRAL'
      END AS alignment,
      COALESCE(p6_weight, 0.55) * COALESCE(narrative_gap, 0.5) AS force_score
    FROM contradiction_force
  )
  SELECT
    COALESCE(SUM(CASE WHEN alignment = 'A' THEN force_score ELSE 0 END), 0),
    COALESCE(SUM(CASE WHEN alignment = 'B' THEN force_score ELSE 0 END), 0),
    COALESCE(SUM(CASE WHEN alignment = 'NEUTRAL' THEN force_score ELSE 0 END), 0),
    COALESCE(jsonb_agg(jsonb_build_object(
      'id', id,
      'alignment', alignment,
      'force_score', round(force_score::numeric, 4),
      'has_t6', has_t6,
      'hard_hit_a', hard_hit_a,
      'hard_hit_b', hard_hit_b,
      'official_hit_a', official_hit_a,
      'official_hit_b', official_hit_b,
      'p6_weight', round(COALESCE(p6_weight, 0.55)::numeric, 4),
      'narrative_gap', narrative_gap,
      'official_narrative', official_narrative
    ) ORDER BY force_score DESC), '[]'::jsonb)
  INTO v_resonance, v_friction, v_neutral, v_alignment
  FROM routed;

  v_total_force := v_resonance + v_friction + v_neutral;

  v_confidence := CASE
    WHEN v_total_force <= 0 THEN 0.50
    ELSE LEAST(0.95, GREATEST(0.30,
      0.50
      + (v_resonance / v_total_force) * 0.35
      - (v_friction / v_total_force) * 0.25
      - (v_neutral / v_total_force) * 0.05
    ))
  END;

  RETURN jsonb_build_object(
    'ok', true,
    'version', 'forecast_v1.1',
    'entity', p_entity_name,
    'route_profile', v_route_profile,
    'generated_at', now(),

    'decision', CASE
      WHEN v_prob_a >= v_prob_b THEN 'A'
      ELSE 'B'
    END,

    'panel_1_pressure', jsonb_build_object(
      'pressure_level', v_pressure,
      'trend', v_trend,
      'risk_level', v_trajectory->>'risk_level',
      'dominant_mode', v_profile->>'survival_mode',
      'essence', v_profile->>'essence',
      'key_drivers', v_trajectory->'key_drivers',
      'mirror_bias', v_profile->>'mirror_bias'
    ),

    'panel_2_timeline', jsonb_build_object(
      'nodes', v_timeline,
      'active_signals', v_signals,
      'contradictions', v_contradictions
    ),

    'panel_3_forecast', jsonb_build_object(
      'horizon_months', COALESCE((v_trajectory->>'prediction_horizon')::int, 12),
      'option_a', v_forecast_a,
      'prob_a', round(v_prob_a::numeric, 2),
      'option_b', v_forecast_b,
      'prob_b', round(v_prob_b::numeric, 2),
      'confidence', round(v_confidence::numeric, 2),
      'top_behaviors', v_behaviors,
      'prediction_text', v_trajectory->>'prediction'
    ),

    'panel_4_signal_alignment', jsonb_build_object(
      'model', 'resonance_friction_v1',
      'resonance_score', round(v_resonance::numeric, 4),
      'friction_score', round(v_friction::numeric, 4),
      'neutral_score', round(v_neutral::numeric, 4),
      'confidence', round(v_confidence::numeric, 2),
      'rules', jsonb_build_object(
        'probability', 'internal_behavior_model',
        'confidence', 'external_signal_resonance',
        't6_official_b', 'route_specific',
        't6_official_a', 'route_specific',
        'route_profile', v_route_profile
      ),
      'alignment_details', COALESCE(v_alignment, '[]'::jsonb)
    )
  );
END;
$function$
;

-- Function: ccc.forecast_v1_1(text)
CREATE OR REPLACE FUNCTION ccc.forecast_v1_1(p_entity_name text)
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE
AS $function$
DECLARE
  v_base jsonb;
  v_gate jsonb;

  v_resonance double precision := 0.0;
  v_friction  double precision := 0.0;
  v_neutral   double precision := 0.0;

  v_confidence numeric := 0.50;
  v_evidence_score numeric := 0.0;
  v_direction_balance numeric := 0.0;
  v_total_force numeric := 0.0;
BEGIN
  -- 调用原始核心函数
  v_base := ccc.forecast_v1_1_core(p_entity_name);

  -- 如果实体不存在，原样返回
  IF COALESCE((v_base->>'ok')::boolean, false) IS NOT TRUE THEN
    RETURN v_base;
  END IF;

  -- 读取核心函数已经算好的三类应力
  v_resonance := COALESCE((v_base #>> '{panel_4_signal_alignment,resonance_score}')::double precision, 0.0);
  v_friction  := COALESCE((v_base #>> '{panel_4_signal_alignment,friction_score}')::double precision, 0.0);
  v_neutral   := COALESCE((v_base #>> '{panel_4_signal_alignment,neutral_score}')::double precision, 0.0);

  -- 新置信度门控
  v_gate := ccc.forecast_confidence_gate_v1(v_resonance, v_friction, v_neutral);

  v_confidence        := (v_gate->>'confidence')::numeric;
  v_evidence_score    := (v_gate->>'evidence_score')::numeric;
  v_direction_balance := (v_gate->>'direction_balance')::numeric;
  v_total_force       := (v_gate->>'total_force')::numeric;

  -- 标记版本
  v_base := jsonb_set(
    v_base,
    '{version}',
    to_jsonb('forecast_v1.1-confidence_gate'::text),
    true
  );

  -- 写回 panel_3_forecast.confidence
  v_base := jsonb_set(
    v_base,
    '{panel_3_forecast,confidence}',
    to_jsonb(round(v_confidence, 2)),
    true
  );

  -- 写回 panel_4_signal_alignment.confidence
  v_base := jsonb_set(
    v_base,
    '{panel_4_signal_alignment,confidence}',
    to_jsonb(round(v_confidence, 2)),
    true
  );

  -- 增加证据量解释字段
  v_base := jsonb_set(
    v_base,
    '{panel_4_signal_alignment,total_force}',
    to_jsonb(round(v_total_force, 4)),
    true
  );

  v_base := jsonb_set(
    v_base,
    '{panel_4_signal_alignment,evidence_score}',
    to_jsonb(round(v_evidence_score, 4)),
    true
  );

  v_base := jsonb_set(
    v_base,
    '{panel_4_signal_alignment,direction_balance}',
    to_jsonb(round(v_direction_balance, 4)),
    true
  );

  v_base := jsonb_set(
    v_base,
    '{panel_4_signal_alignment,confidence_model}',
    to_jsonb('confidence_evidence_gate_v1'::text),
    true
  );

  RETURN v_base;
END;
$function$
;

-- ============================================================
-- Checkpoint tables
-- ============================================================


CREATE TABLE IF NOT EXISTS ccc.rsal_checkpoints (
  id bigserial PRIMARY KEY,
  checkpoint_label text UNIQUE NOT NULL,
  module text NOT NULL,
  note text,
  created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ccc.function_snapshots (
  id bigserial PRIMARY KEY,
  checkpoint_label text NOT NULL,
  function_signature text NOT NULL,
  function_definition text NOT NULL,
  definition_hash text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  UNIQUE (checkpoint_label, function_signature)
);

CREATE TABLE IF NOT EXISTS ccc.forecast_regression_expectations (
  entity_name text PRIMARY KEY,
  expected_route_profile text NOT NULL,
  expected_option_a text NOT NULL,
  expected_option_b text NOT NULL,
  min_confidence numeric NOT NULL,
  max_confidence numeric NOT NULL,
  min_total_force numeric NOT NULL,
  max_total_force numeric NOT NULL,
  expected_direction text NOT NULL,
  note text,
  updated_at timestamp with time zone DEFAULT now()
);

INSERT INTO ccc.rsal_checkpoints (checkpoint_label, module, note, created_at) VALUES ('P7.3d_forecast_v1_1_confidence_gate_stable', 'P7 Survival Forecast', 'Stable checkpoint: entity audit + route-specific semantics + confidence evidence gate. No P7.4 rigidity multiplier yet.', '2026-06-05T18:49:31.590412+12:00'::timestamptz)
ON CONFLICT (checkpoint_label) DO UPDATE SET
  module = EXCLUDED.module,
  note = EXCLUDED.note,
  created_at = EXCLUDED.created_at;

INSERT INTO ccc.function_snapshots (checkpoint_label, function_signature, function_definition, definition_hash, created_at) VALUES ('P7.3d_forecast_v1_1_confidence_gate_stable', 'ccc.forecast_confidence_gate_v1(double precision, double precision, double precision)', 'CREATE OR REPLACE FUNCTION ccc.forecast_confidence_gate_v1(p_resonance double precision, p_friction double precision, p_neutral double precision)
 RETURNS jsonb
 LANGUAGE plpgsql
 IMMUTABLE
AS $function$
DECLARE
  v_resonance double precision := GREATEST(0.0, COALESCE(p_resonance, 0.0));
  v_friction  double precision := GREATEST(0.0, COALESCE(p_friction, 0.0));
  v_neutral   double precision := GREATEST(0.0, COALESCE(p_neutral, 0.0));

  v_total_force double precision := 0.0;
  v_evidence_score double precision := 0.0;
  v_direction_balance double precision := 0.0;
  v_confidence double precision := 0.50;
BEGIN
  v_total_force := v_resonance + v_friction + v_neutral;

  IF v_total_force <= 0 THEN
    v_evidence_score := 0.0;
    v_direction_balance := 0.0;
    v_confidence := 0.50;
  ELSE
    -- 证据量门控：total_force >= 1.0 视为证据量充足
    v_evidence_score := LEAST(1.0, v_total_force / 1.0);

    -- 方向平衡：
    -- resonance 推高 A 面置信
    -- friction 压低 A 面置信
    -- neutral 只轻微扣分，避免中性噪音过度惩罚
    v_direction_balance :=
      (v_resonance - v_friction - v_neutral * 0.20) / v_total_force;

    v_confidence := LEAST(0.95, GREATEST(0.30,
      0.50 + v_direction_balance * v_evidence_score * 0.35
    ));
  END IF;

  RETURN jsonb_build_object(
    ''confidence'',        round(v_confidence::numeric, 4),
    ''total_force'',       round(v_total_force::numeric, 4),
    ''evidence_score'',    round(v_evidence_score::numeric, 4),
    ''direction_balance'', round(v_direction_balance::numeric, 4),
    ''model'',             ''confidence_evidence_gate_v1'',
    ''formula'',           ''0.50 + direction_balance * evidence_score * 0.35''
  );
END;
$function$
', 'c824a6f59e488cf3b9e3aa80a1363fa6', '2026-06-05T18:49:31.590412+12:00'::timestamptz)
ON CONFLICT (checkpoint_label, function_signature) DO UPDATE SET
  function_definition = EXCLUDED.function_definition,
  definition_hash = EXCLUDED.definition_hash,
  created_at = EXCLUDED.created_at;

INSERT INTO ccc.function_snapshots (checkpoint_label, function_signature, function_definition, definition_hash, created_at) VALUES ('P7.3d_forecast_v1_1_confidence_gate_stable', 'ccc.forecast_v1_1_core(text)', 'CREATE OR REPLACE FUNCTION ccc.forecast_v1_1_core(p_entity_name text)
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE
AS $function$
DECLARE
  v_keywords_a text[] := ARRAY[
    ''监管'',''打压'',''审查'',''维稳'',''资本管制'',''收紧'',''收缩'',''清洗'',''反腐'',''国家安全'',''外部势力'',''军事演习'',''统一'',''制裁'',''管控'',''严打'',''斗争'',
    ''監管'',''打壓'',''審查'',''維穩'',''資本管制'',''收緊'',''收縮'',''清洗'',''反腐'',''國家安全'',''外部勢力'',''軍事演習'',''統一'',''制裁'',''管控'',''嚴打'',''鬥爭'',
    ''crackdown'',''tightening'',''control'',''regulation'',''censorship'',''security'',''purge'',''anti-corruption'',''military drill'',''sanction'',''national security'',''containment'',
    ''規制'',''弾圧'',''検閲'',''統制'',''安全保障'',''粛清'',''反腐敗'',''軍事演習'',''制裁'',''管理強化'',''台湾有事'',''対中強硬'',
    ''jianguan'',''daji'',''shencha'',''weiwen'',''shoujin'',''shousuo'',''qingxi'',''fanfu'',''guankong'',''guoan'',''junshiyanxi'',''zhicai''
  ];

  v_keywords_b text[] := ARRAY[
    ''开放'',''放宽'',''改革'',''市场化'',''民营'',''松绑'',''宽松'',''刺激'',''减税'',''外资'',''营商环境'',''合作'',''谈判'',''缓和'',
    ''開放'',''放寬'',''改革'',''市場化'',''民營'',''鬆綁'',''寬鬆'',''刺激'',''減稅'',''外資'',''營商環境'',''合作'',''談判'',''緩和'',
    ''opening'',''liberalization'',''reform'',''marketization'',''private sector'',''easing'',''stimulus'',''tax cut'',''foreign investment'',''cooperation'',''negotiation'',''de-escalation'',
    ''開放'',''緩和'',''改革'',''自由化'',''市場化'',''民営化'',''金融緩和'',''刺激策'',''減税'',''外資誘致'',''協力'',''交渉'',''対話'',''関係改善'',
    ''kaifang'',''fangkuan'',''gaige'',''shichanghua'',''minying'',''songbang'',''kuansong'',''ciji'',''jianshui'',''waizi'',''hezuo'',''tanpan'',''huanhe''
  ];

  v_profile jsonb := ''{}''::jsonb;
  v_trajectory jsonb := ''{}''::jsonb;
  v_signals jsonb := ''[]''::jsonb;
  v_contradictions jsonb := ''[]''::jsonb;
  v_behaviors jsonb := ''[]''::jsonb;
  v_timeline jsonb := ''[]''::jsonb;
  v_alignment jsonb := ''[]''::jsonb;

  v_entity_id bigint;
  v_profile_id bigint;
  v_route_profile text := ''neutral_agent'';

  v_pressure float := 0.5;
  v_trend text := ''stable'';
  v_forecast_a text := ''强化现有路线'';
  v_forecast_b text := ''路线调整'';
  v_prob_a float := 0.55;
  v_prob_b float := 0.45;

  v_resonance float := 0;
  v_friction float := 0;
  v_neutral float := 0;
  v_total_force float := 0;
  v_confidence float := 0.5;
BEGIN
  SELECT ep.id, ep.entity_id,
         jsonb_build_object(
           ''essence'', ep.essence,
           ''survival_mode'', ep.survival_mode,
           ''mirror_bias'', ep.mirror_bias,
           ''core_drives'', ep.core_drives,
           ''behavior_pattern'', ep.behavior_pattern,
           ''confidence'', ep.confidence
         )
  INTO v_profile_id, v_entity_id, v_profile
  FROM ccc.entity_profiles ep
  WHERE lower(ep.entity_name) = lower(p_entity_name)
  LIMIT 1;

  IF v_profile_id IS NULL THEN
    RETURN jsonb_build_object(
      ''ok'', false,
      ''error'', ''entity profile not found'',
      ''entity'', p_entity_name
    );
  END IF;

  SELECT jsonb_build_object(
           ''pressure'', et.pressure,
           ''pressure_trend'', et.pressure_trend,
           ''trajectory_status'', et.trajectory_status,
           ''risk_level'', et.risk_level,
           ''key_drivers'', et.key_drivers,
           ''supporting_signals'', et.supporting_signals,
           ''next_possible_events'', et.next_possible_events,
           ''prediction'', et.short_term_prediction,
           ''prediction_horizon'', et.prediction_horizon,
           ''confidence'', et.confidence
         )
  INTO v_trajectory
  FROM ccc.entity_trajectories et
  WHERE et.entity_profile_id = v_profile_id
  ORDER BY et.snapshot_date DESC
  LIMIT 1;

  v_pressure := COALESCE((v_trajectory->>''pressure'')::float, 0.5);
  v_trend := COALESCE(v_trajectory->>''pressure_trend'', ''stable'');

  -- P7.3b route_profile mapping
  v_route_profile := CASE
    WHEN v_profile->>''survival_mode'' IN (''权力集中化'', ''政权延续'', ''地缘安全扩张'')
      THEN ''authoritarian''
    WHEN v_profile->>''survival_mode'' IN (''交易利益最大化'', ''重新定价与秩序解构'')
      THEN ''transactional''
    WHEN v_profile->>''survival_mode'' IN (''流动性管理'', ''美元体系稳定管理'')
      THEN ''financial''
    WHEN v_profile->>''survival_mode'' IN (''议程设定'', ''精英治理议程设定'')
      THEN ''governance''
    ELSE ''neutral_agent''
  END;

  SELECT COALESCE(jsonb_agg(x.obj ORDER BY x.strength DESC), ''[]''::jsonb)
  INTO v_signals
  FROM (
    SELECT
      s.strength,
      jsonb_build_object(
        ''type'', s.signal_type,
        ''text'', s.signal_text,
        ''strength'', s.strength,
        ''trigger_condition'', s.trigger_condition,
        ''linked_prediction'', s.linked_prediction,
        ''source'', s.source_label
      ) AS obj
    FROM ccc.signals s
    WHERE s.entity_profile_id = v_profile_id
      AND s.is_active = true
    ORDER BY s.strength DESC
    LIMIT 5
  ) x;

  SELECT COALESCE(jsonb_agg(x.obj ORDER BY x.gap DESC), ''[]''::jsonb)
  INTO v_contradictions
  FROM (
    SELECT
      ce.narrative_gap AS gap,
      jsonb_build_object(
        ''official'', ce.official_narrative,
        ''counter_signals'', ce.counter_signals,
        ''real_indicators'', ce.real_indicators,
        ''gap'', ce.narrative_gap,
        ''severity'', ce.severity,
        ''confidence_decay'', ce.confidence_decay,
        ''source_labels'', ce.source_labels,
        ''trust_levels'', ce.trust_levels
      ) AS obj
    FROM ccc.contradiction_engine ce
    WHERE ce.entity_id = v_entity_id
      AND ce.is_active = true
    ORDER BY ce.narrative_gap DESC
    LIMIT 5
  ) x;

  SELECT COALESCE(jsonb_agg(x.obj ORDER BY x.confidence DESC), ''[]''::jsonb)
  INTO v_behaviors
  FROM (
    SELECT
      bm.confidence,
      jsonb_build_object(
        ''prediction'', bm.predicted_action,
        ''type'', bm.action_type,
        ''confidence'', bm.confidence,
        ''historical_accuracy'', bm.historical_accuracy,
        ''horizon'', bm.time_horizon,
        ''triggers'', bm.trigger_conditions,
        ''counter_signals'', bm.counter_signals
      ) AS obj
    FROM ccc.behavioral_models bm
    WHERE bm.entity_profile_id = v_profile_id
    ORDER BY bm.confidence DESC
    LIMIT 3
  ) x;

  SELECT COALESCE(jsonb_agg(x.obj ORDER BY x.event_time), ''[]''::jsonb)
  INTO v_timeline
  FROM (
    SELECT
      en.event_time,
      jsonb_build_object(
        ''time'', en.event_time,
        ''sequence_order'', en.sequence_order,
        ''essence'', en.essence,
        ''mechanism'', en.mechanism,
        ''pressure'', en.pressure,
        ''signal_strength'', en.signal_strength,
        ''causal_weight'', en.causal_weight,
        ''escalation_score'', en.escalation_score
      ) AS obj
    FROM ccc.event_nodes en
    JOIN ccc.event_chains ec ON ec.id = en.chain_id
    WHERE ec.entity_id = v_entity_id
    ORDER BY en.event_time DESC
    LIMIT 5
  ) x;

  v_prob_a := CASE
    WHEN v_pressure >= 0.8 AND v_trend = ''rising'' THEN 0.78
    WHEN v_pressure >= 0.7 AND v_trend = ''rising'' THEN 0.68
    WHEN v_pressure >= 0.6 AND v_trend = ''stable'' THEN 0.58
    WHEN v_pressure >= 0.5 AND v_trend = ''declining'' THEN 0.45
    ELSE 0.55
  END;

  v_prob_b := 1.0 - v_prob_a;

  -- P7.3b option A
  v_forecast_a := CASE v_profile->>''survival_mode''
    WHEN ''权力集中化'' THEN ''权力绝对集中''
    WHEN ''地缘安全扩张'' THEN ''军事行动升级''
    WHEN ''交易利益最大化'' THEN ''单边交易强化''
    WHEN ''重新定价与秩序解构'' THEN ''破坏性极限施压''
    WHEN ''政权延续'' THEN ''刚性社会维稳''
    WHEN ''流动性管理'' THEN ''流动性干预''
    WHEN ''美元体系稳定管理'' THEN ''流动性救市''
    WHEN ''议程设定'' THEN ''治理框架推进''
    WHEN ''精英治理议程设定'' THEN ''全球协调增强 / 精英治理深化''
    ELSE ''强化现有路线''
  END;

  -- P7.3b option B
  v_forecast_b := CASE v_profile->>''survival_mode''
    WHEN ''权力集中化'' THEN ''战术性防御退让''
    WHEN ''地缘安全扩张'' THEN ''战略收缩 / 外交谈判''
    WHEN ''交易利益最大化'' THEN ''多边合作''
    WHEN ''重新定价与秩序解构'' THEN ''协议达成与筹码套现''
    WHEN ''政权延续'' THEN ''市场化自救放权''
    WHEN ''流动性管理'' THEN ''货币收紧''
    WHEN ''美元体系稳定管理'' THEN ''纪律性紧缩''
    WHEN ''议程设定'' THEN ''主权让步''
    WHEN ''精英治理议程设定'' THEN ''国家主权反弹 / 逆全球化加深''
    ELSE ''路线调整''
  END;

  WITH contradiction_force AS (
    SELECT
      ce.id,
      ce.official_narrative,
      array_to_string(ce.counter_signals, '' '') AS counter_text,
      array_to_string(ce.real_indicators, '' '') AS real_text,
      ce.narrative_gap,
      ce.source_labels,
      ce.trust_levels,

      EXISTS (
        SELECT 1 FROM unnest(v_keywords_a) kw
        WHERE array_to_string(ce.counter_signals, '' '') ILIKE ''%'' || kw || ''%''
           OR array_to_string(ce.real_indicators, '' '') ILIKE ''%'' || kw || ''%''
      ) AS hard_hit_a,

      EXISTS (
        SELECT 1 FROM unnest(v_keywords_b) kw
        WHERE array_to_string(ce.counter_signals, '' '') ILIKE ''%'' || kw || ''%''
           OR array_to_string(ce.real_indicators, '' '') ILIKE ''%'' || kw || ''%''
      ) AS hard_hit_b,

      EXISTS (
        SELECT 1 FROM unnest(v_keywords_a) kw
        WHERE ce.official_narrative ILIKE ''%'' || kw || ''%''
      ) AS official_hit_a,

      EXISTS (
        SELECT 1 FROM unnest(v_keywords_b) kw
        WHERE ce.official_narrative ILIKE ''%'' || kw || ''%''
      ) AS official_hit_b,

      EXISTS (
        SELECT 1 FROM unnest(ce.trust_levels) tl
        WHERE tl = ''T6''
      ) AS has_t6,

      (
        SELECT AVG(
          COALESCE(
            (
              ccc.source_effective_weight(sl.label::text, NULL::text, NULL::text)
              ->''weights''->>''reverse_indicator_weight''
            )::double precision,
            CASE
              WHEN sl.trust_level = ''T6'' THEN 0.65
              WHEN sl.trust_level = ''T3'' THEN 0.70
              WHEN sl.trust_level = ''T2'' THEN 0.60
              ELSE 0.55
            END
          )
          *
          CASE WHEN sl.trust_level = ''T6'' THEN 1.10 ELSE 1.00 END
        )
        FROM (
          SELECT
            labels.label,
            COALESCE(levels.trust_level, ''UNK'') AS trust_level
          FROM unnest(ce.source_labels) WITH ORDINALITY labels(label, ord)
          LEFT JOIN unnest(ce.trust_levels) WITH ORDINALITY levels(trust_level, ord)
            ON labels.ord = levels.ord
        ) sl
      ) AS p6_weight

    FROM ccc.contradiction_engine ce
    WHERE ce.entity_id = v_entity_id
      AND ce.is_active = true
  ),
  routed AS (
    SELECT
      *,
      CASE
        -- Authoritarian
        WHEN v_route_profile = ''authoritarian''
         AND has_t6
         AND (
           official_narrative ILIKE ''%透明通报%''
           OR official_narrative ILIKE ''%自然界%''
           OR official_narrative ILIKE ''%源于自然%''
           OR official_narrative ILIKE ''%开放包容%''
           OR official_narrative ILIKE ''%合作共赢%''
           OR official_narrative ILIKE ''%和平解决%''
           OR official_narrative ILIKE ''%无意动武%''
           OR official_narrative ILIKE ''%自由贸易%''
           OR official_narrative ILIKE ''%自由贸易秩序%''
           OR official_narrative ILIKE ''%重要力量%''
           OR official_narrative ILIKE ''%保持稳定%''
           OR official_narrative ILIKE ''%稳定复苏%''
           OR official_narrative ILIKE ''%改革开放%''
           OR official_narrative ILIKE ''%持续深化%''
         )
          THEN ''A''

        WHEN v_route_profile = ''authoritarian''
         AND (
           counter_text ILIKE ''%军事演习%'' OR real_text ILIKE ''%军事演习%''
           OR counter_text ILIKE ''%统一时间表%'' OR real_text ILIKE ''%统一时间表%''
           OR counter_text ILIKE ''%样本销毁%'' OR real_text ILIKE ''%样本销毁%''
           OR counter_text ILIKE ''%调查受限%'' OR real_text ILIKE ''%调查受限%''
           OR counter_text ILIKE ''%预警压制%'' OR real_text ILIKE ''%预警压制%''
           OR counter_text ILIKE ''%出口限制%'' OR real_text ILIKE ''%出口限制%''
           OR counter_text ILIKE ''%供应链切断%'' OR real_text ILIKE ''%供应链切断%''
           OR counter_text ILIKE ''%贸易武器化%'' OR real_text ILIKE ''%贸易武器化%''
           OR counter_text ILIKE ''%技术脱钩%'' OR real_text ILIKE ''%技术脱钩%''
           OR counter_text ILIKE ''%关键矿产%'' OR real_text ILIKE ''%关键矿产%''
           OR counter_text ILIKE ''%债务陷阱%'' OR real_text ILIKE ''%债务陷阱%''
           OR counter_text ILIKE ''%经济胁迫%'' OR real_text ILIKE ''%经济胁迫%''
         )
          THEN ''A''

        -- Governance
        WHEN v_route_profile = ''governance''
         AND (
           official_narrative ILIKE ''%全球治理%''
           OR official_narrative ILIKE ''%自由贸易%''
           OR official_narrative ILIKE ''%服务全人类%''
           OR official_narrative ILIKE ''%开放包容%''
           OR official_narrative ILIKE ''%利益相关者%''
         )
          THEN ''B''

        -- Financial
        WHEN v_route_profile = ''financial''
         AND (
           real_text ILIKE ''%政治施压%''
           OR counter_text ILIKE ''%政治施压%''
           OR real_text ILIKE ''%听证施压%''
           OR counter_text ILIKE ''%听证施压%''
           OR real_text ILIKE ''%任命政治化%''
           OR counter_text ILIKE ''%任命政治化%''
           OR real_text ILIKE ''%政治周期%''
           OR counter_text ILIKE ''%政治周期%''
           OR real_text ILIKE ''%MMT%''
           OR counter_text ILIKE ''%MMT%''
           OR real_text ILIKE ''%流动性锁死%''
           OR counter_text ILIKE ''%流动性锁死%''
         )
          THEN ''A''

        WHEN v_route_profile = ''financial''
         AND (
           official_narrative ILIKE ''%独立%''
           OR official_narrative ILIKE ''%基于数据%''
           OR official_narrative ILIKE ''%保持稳定%''
           OR official_narrative ILIKE ''%符合预期%''
         )
          THEN ''NEUTRAL''

        -- Transactional
        WHEN v_route_profile = ''transactional''
         AND (
           counter_text ILIKE ''%技术脱钩%'' OR real_text ILIKE ''%技术脱钩%''
           OR counter_text ILIKE ''%加征关税%'' OR real_text ILIKE ''%加征关税%''
           OR counter_text ILIKE ''%关税%'' OR real_text ILIKE ''%关税%''
           OR counter_text ILIKE ''%极限施压%'' OR real_text ILIKE ''%极限施压%''
           OR counter_text ILIKE ''%供应链重组%'' OR real_text ILIKE ''%供应链重组%''
           OR counter_text ILIKE ''%单边%'' OR real_text ILIKE ''%单边%''
         )
          THEN ''A''

        WHEN v_route_profile = ''transactional''
         AND (
           official_narrative ILIKE ''%极好的协议%''
           OR official_narrative ILIKE ''%随时谈判%''
           OR official_narrative ILIKE ''%目标有限%''
           OR official_narrative ILIKE ''%可以谈判%''
         )
          THEN ''B''

        -- Global residual
        WHEN (
           counter_text ILIKE ''%宣战%'' OR real_text ILIKE ''%宣战%''
           OR counter_text ILIKE ''%全面制裁%'' OR real_text ILIKE ''%全面制裁%''
           OR counter_text ILIKE ''%全面戒严%'' OR real_text ILIKE ''%全面戒严%''
           OR counter_text ILIKE ''%切断代理行%'' OR real_text ILIKE ''%切断代理行%''
        )
          THEN ''A''

        ELSE ''NEUTRAL''
      END AS alignment,
      COALESCE(p6_weight, 0.55) * COALESCE(narrative_gap, 0.5) AS force_score
    FROM contradiction_force
  )
  SELECT
    COALESCE(SUM(CASE WHEN alignment = ''A'' THEN force_score ELSE 0 END), 0),
    COALESCE(SUM(CASE WHEN alignment = ''B'' THEN force_score ELSE 0 END), 0),
    COALESCE(SUM(CASE WHEN alignment = ''NEUTRAL'' THEN force_score ELSE 0 END), 0),
    COALESCE(jsonb_agg(jsonb_build_object(
      ''id'', id,
      ''alignment'', alignment,
      ''force_score'', round(force_score::numeric, 4),
      ''has_t6'', has_t6,
      ''hard_hit_a'', hard_hit_a,
      ''hard_hit_b'', hard_hit_b,
      ''official_hit_a'', official_hit_a,
      ''official_hit_b'', official_hit_b,
      ''p6_weight'', round(COALESCE(p6_weight, 0.55)::numeric, 4),
      ''narrative_gap'', narrative_gap,
      ''official_narrative'', official_narrative
    ) ORDER BY force_score DESC), ''[]''::jsonb)
  INTO v_resonance, v_friction, v_neutral, v_alignment
  FROM routed;

  v_total_force := v_resonance + v_friction + v_neutral;

  v_confidence := CASE
    WHEN v_total_force <= 0 THEN 0.50
    ELSE LEAST(0.95, GREATEST(0.30,
      0.50
      + (v_resonance / v_total_force) * 0.35
      - (v_friction / v_total_force) * 0.25
      - (v_neutral / v_total_force) * 0.05
    ))
  END;

  RETURN jsonb_build_object(
    ''ok'', true,
    ''version'', ''forecast_v1.1'',
    ''entity'', p_entity_name,
    ''route_profile'', v_route_profile,
    ''generated_at'', now(),

    ''decision'', CASE
      WHEN v_prob_a >= v_prob_b THEN ''A''
      ELSE ''B''
    END,

    ''panel_1_pressure'', jsonb_build_object(
      ''pressure_level'', v_pressure,
      ''trend'', v_trend,
      ''risk_level'', v_trajectory->>''risk_level'',
      ''dominant_mode'', v_profile->>''survival_mode'',
      ''essence'', v_profile->>''essence'',
      ''key_drivers'', v_trajectory->''key_drivers'',
      ''mirror_bias'', v_profile->>''mirror_bias''
    ),

    ''panel_2_timeline'', jsonb_build_object(
      ''nodes'', v_timeline,
      ''active_signals'', v_signals,
      ''contradictions'', v_contradictions
    ),

    ''panel_3_forecast'', jsonb_build_object(
      ''horizon_months'', COALESCE((v_trajectory->>''prediction_horizon'')::int, 12),
      ''option_a'', v_forecast_a,
      ''prob_a'', round(v_prob_a::numeric, 2),
      ''option_b'', v_forecast_b,
      ''prob_b'', round(v_prob_b::numeric, 2),
      ''confidence'', round(v_confidence::numeric, 2),
      ''top_behaviors'', v_behaviors,
      ''prediction_text'', v_trajectory->>''prediction''
    ),

    ''panel_4_signal_alignment'', jsonb_build_object(
      ''model'', ''resonance_friction_v1'',
      ''resonance_score'', round(v_resonance::numeric, 4),
      ''friction_score'', round(v_friction::numeric, 4),
      ''neutral_score'', round(v_neutral::numeric, 4),
      ''confidence'', round(v_confidence::numeric, 2),
      ''rules'', jsonb_build_object(
        ''probability'', ''internal_behavior_model'',
        ''confidence'', ''external_signal_resonance'',
        ''t6_official_b'', ''route_specific'',
        ''t6_official_a'', ''route_specific'',
        ''route_profile'', v_route_profile
      ),
      ''alignment_details'', COALESCE(v_alignment, ''[]''::jsonb)
    )
  );
END;
$function$
', '9346a79f2462ee513a1f732bff6948ed', '2026-06-05T18:49:31.590412+12:00'::timestamptz)
ON CONFLICT (checkpoint_label, function_signature) DO UPDATE SET
  function_definition = EXCLUDED.function_definition,
  definition_hash = EXCLUDED.definition_hash,
  created_at = EXCLUDED.created_at;

INSERT INTO ccc.function_snapshots (checkpoint_label, function_signature, function_definition, definition_hash, created_at) VALUES ('P7.3d_forecast_v1_1_confidence_gate_stable', 'ccc.forecast_v1_1(text)', 'CREATE OR REPLACE FUNCTION ccc.forecast_v1_1(p_entity_name text)
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE
AS $function$
DECLARE
  v_base jsonb;
  v_gate jsonb;

  v_resonance double precision := 0.0;
  v_friction  double precision := 0.0;
  v_neutral   double precision := 0.0;

  v_confidence numeric := 0.50;
  v_evidence_score numeric := 0.0;
  v_direction_balance numeric := 0.0;
  v_total_force numeric := 0.0;
BEGIN
  -- 调用原始核心函数
  v_base := ccc.forecast_v1_1_core(p_entity_name);

  -- 如果实体不存在，原样返回
  IF COALESCE((v_base->>''ok'')::boolean, false) IS NOT TRUE THEN
    RETURN v_base;
  END IF;

  -- 读取核心函数已经算好的三类应力
  v_resonance := COALESCE((v_base #>> ''{panel_4_signal_alignment,resonance_score}'')::double precision, 0.0);
  v_friction  := COALESCE((v_base #>> ''{panel_4_signal_alignment,friction_score}'')::double precision, 0.0);
  v_neutral   := COALESCE((v_base #>> ''{panel_4_signal_alignment,neutral_score}'')::double precision, 0.0);

  -- 新置信度门控
  v_gate := ccc.forecast_confidence_gate_v1(v_resonance, v_friction, v_neutral);

  v_confidence        := (v_gate->>''confidence'')::numeric;
  v_evidence_score    := (v_gate->>''evidence_score'')::numeric;
  v_direction_balance := (v_gate->>''direction_balance'')::numeric;
  v_total_force       := (v_gate->>''total_force'')::numeric;

  -- 标记版本
  v_base := jsonb_set(
    v_base,
    ''{version}'',
    to_jsonb(''forecast_v1.1-confidence_gate''::text),
    true
  );

  -- 写回 panel_3_forecast.confidence
  v_base := jsonb_set(
    v_base,
    ''{panel_3_forecast,confidence}'',
    to_jsonb(round(v_confidence, 2)),
    true
  );

  -- 写回 panel_4_signal_alignment.confidence
  v_base := jsonb_set(
    v_base,
    ''{panel_4_signal_alignment,confidence}'',
    to_jsonb(round(v_confidence, 2)),
    true
  );

  -- 增加证据量解释字段
  v_base := jsonb_set(
    v_base,
    ''{panel_4_signal_alignment,total_force}'',
    to_jsonb(round(v_total_force, 4)),
    true
  );

  v_base := jsonb_set(
    v_base,
    ''{panel_4_signal_alignment,evidence_score}'',
    to_jsonb(round(v_evidence_score, 4)),
    true
  );

  v_base := jsonb_set(
    v_base,
    ''{panel_4_signal_alignment,direction_balance}'',
    to_jsonb(round(v_direction_balance, 4)),
    true
  );

  v_base := jsonb_set(
    v_base,
    ''{panel_4_signal_alignment,confidence_model}'',
    to_jsonb(''confidence_evidence_gate_v1''::text),
    true
  );

  RETURN v_base;
END;
$function$
', '2573def9dfb96f42d30cefd1bd920f68', '2026-06-05T18:49:31.590412+12:00'::timestamptz)
ON CONFLICT (checkpoint_label, function_signature) DO UPDATE SET
  function_definition = EXCLUDED.function_definition,
  definition_hash = EXCLUDED.definition_hash,
  created_at = EXCLUDED.created_at;

INSERT INTO ccc.forecast_regression_expectations (entity_name, expected_route_profile, expected_option_a, expected_option_b, min_confidence, max_confidence, min_total_force, max_total_force, expected_direction, note, updated_at) VALUES ('WEF', 'governance', '全球协调增强 / 精英治理深化', '国家主权反弹 / 逆全球化加深', 0.33, 0.37, 0.41, 0.43, 'B_FRICTION', 'Governance 场中开放包容/全球治理顺推为 B 面摩擦', '2026-06-05T18:49:31.590412+12:00'::timestamptz)
ON CONFLICT (entity_name) DO UPDATE SET
  expected_route_profile = EXCLUDED.expected_route_profile,
  expected_option_a = EXCLUDED.expected_option_a,
  expected_option_b = EXCLUDED.expected_option_b,
  min_confidence = EXCLUDED.min_confidence,
  max_confidence = EXCLUDED.max_confidence,
  min_total_force = EXCLUDED.min_total_force,
  max_total_force = EXCLUDED.max_total_force,
  expected_direction = EXCLUDED.expected_direction,
  note = EXCLUDED.note,
  updated_at = EXCLUDED.updated_at;

INSERT INTO ccc.forecast_regression_expectations (entity_name, expected_route_profile, expected_option_a, expected_option_b, min_confidence, max_confidence, min_total_force, max_total_force, expected_direction, note, updated_at) VALUES ('中共', 'authoritarian', '刚性社会维稳', '市场化自救放权', 0.84, 0.86, 1.16, 1.19, 'A_RESONANCE', '体制基本盘；透明通报/自由贸易秩序进入 Authoritarian 反转逻辑', '2026-06-05T18:49:31.590412+12:00'::timestamptz)
ON CONFLICT (entity_name) DO UPDATE SET
  expected_route_profile = EXCLUDED.expected_route_profile,
  expected_option_a = EXCLUDED.expected_option_a,
  expected_option_b = EXCLUDED.expected_option_b,
  min_confidence = EXCLUDED.min_confidence,
  max_confidence = EXCLUDED.max_confidence,
  min_total_force = EXCLUDED.min_total_force,
  max_total_force = EXCLUDED.max_total_force,
  expected_direction = EXCLUDED.expected_direction,
  note = EXCLUDED.note,
  updated_at = EXCLUDED.updated_at;

INSERT INTO ccc.forecast_regression_expectations (entity_name, expected_route_profile, expected_option_a, expected_option_b, min_confidence, max_confidence, min_total_force, max_total_force, expected_direction, note, updated_at) VALUES ('习近平', 'authoritarian', '权力绝对集中', '战术性防御退让', 0.84, 0.86, 1.10, 1.13, 'A_RESONANCE', '核心实体；T6 镜像反转与硬事实共振成立', '2026-06-05T18:49:31.590412+12:00'::timestamptz)
ON CONFLICT (entity_name) DO UPDATE SET
  expected_route_profile = EXCLUDED.expected_route_profile,
  expected_option_a = EXCLUDED.expected_option_a,
  expected_option_b = EXCLUDED.expected_option_b,
  min_confidence = EXCLUDED.min_confidence,
  max_confidence = EXCLUDED.max_confidence,
  min_total_force = EXCLUDED.min_total_force,
  max_total_force = EXCLUDED.max_total_force,
  expected_direction = EXCLUDED.expected_direction,
  note = EXCLUDED.note,
  updated_at = EXCLUDED.updated_at;

INSERT INTO ccc.forecast_regression_expectations (entity_name, expected_route_profile, expected_option_a, expected_option_b, min_confidence, max_confidence, min_total_force, max_total_force, expected_direction, note, updated_at) VALUES ('特朗普', 'transactional', '破坏性极限施压', '协议达成与筹码套现', 0.49, 0.51, 0.00, 0.00, 'NO_EVIDENCE_NEUTRAL', '暂无 contradiction 样本；保持中立底噪', '2026-06-05T18:49:31.590412+12:00'::timestamptz)
ON CONFLICT (entity_name) DO UPDATE SET
  expected_route_profile = EXCLUDED.expected_route_profile,
  expected_option_a = EXCLUDED.expected_option_a,
  expected_option_b = EXCLUDED.expected_option_b,
  min_confidence = EXCLUDED.min_confidence,
  max_confidence = EXCLUDED.max_confidence,
  min_total_force = EXCLUDED.min_total_force,
  max_total_force = EXCLUDED.max_total_force,
  expected_direction = EXCLUDED.expected_direction,
  note = EXCLUDED.note,
  updated_at = EXCLUDED.updated_at;

INSERT INTO ccc.forecast_regression_expectations (entity_name, expected_route_profile, expected_option_a, expected_option_b, min_confidence, max_confidence, min_total_force, max_total_force, expected_direction, note, updated_at) VALUES ('美联储', 'financial', '流动性救市', '纪律性紧缩', 0.60, 0.64, 0.32, 0.34, 'LOW_EVIDENCE_A', '孤证降权成功；方向纯但证据量不足', '2026-06-05T18:49:31.590412+12:00'::timestamptz)
ON CONFLICT (entity_name) DO UPDATE SET
  expected_route_profile = EXCLUDED.expected_route_profile,
  expected_option_a = EXCLUDED.expected_option_a,
  expected_option_b = EXCLUDED.expected_option_b,
  min_confidence = EXCLUDED.min_confidence,
  max_confidence = EXCLUDED.max_confidence,
  min_total_force = EXCLUDED.min_total_force,
  max_total_force = EXCLUDED.max_total_force,
  expected_direction = EXCLUDED.expected_direction,
  note = EXCLUDED.note,
  updated_at = EXCLUDED.updated_at;

-- ============================================================
-- Regression view
-- ============================================================

CREATE OR REPLACE VIEW ccc.forecast_v1_1_regression AS
 WITH actual AS (
         SELECT e_1.entity_name,
            ccc.forecast_v1_1(e_1.entity_name) AS f
           FROM ccc.forecast_regression_expectations e_1
        ), parsed AS (
         SELECT a.entity_name,
            a.f ->> 'version'::text AS version,
            a.f ->> 'route_profile'::text AS route_profile,
            a.f #>> '{panel_3_forecast,option_a}'::text[] AS option_a,
            a.f #>> '{panel_3_forecast,option_b}'::text[] AS option_b,
            (a.f #>> '{panel_3_forecast,confidence}'::text[])::numeric AS confidence,
            (a.f #>> '{panel_4_signal_alignment,total_force}'::text[])::numeric AS total_force,
            (a.f #>> '{panel_4_signal_alignment,evidence_score}'::text[])::numeric AS evidence_score,
            (a.f #>> '{panel_4_signal_alignment,direction_balance}'::text[])::numeric AS direction_balance,
            (a.f #>> '{panel_4_signal_alignment,resonance_score}'::text[])::numeric AS resonance_score,
            (a.f #>> '{panel_4_signal_alignment,friction_score}'::text[])::numeric AS friction_score,
            (a.f #>> '{panel_4_signal_alignment,neutral_score}'::text[])::numeric AS neutral_score
           FROM actual a
        )
 SELECT p.entity_name,
        CASE
            WHEN p.route_profile = e.expected_route_profile AND p.option_a = e.expected_option_a AND p.option_b = e.expected_option_b AND p.confidence >= e.min_confidence AND p.confidence <= e.max_confidence AND p.total_force >= e.min_total_force AND p.total_force <= e.max_total_force THEN 'PASS'::text
            ELSE 'FAIL'::text
        END AS regression_status,
    p.version,
    p.route_profile,
    e.expected_route_profile,
    p.option_a,
    e.expected_option_a,
    p.option_b,
    e.expected_option_b,
    p.confidence,
    e.min_confidence,
    e.max_confidence,
    p.total_force,
    e.min_total_force,
    e.max_total_force,
    p.evidence_score,
    p.direction_balance,
    p.resonance_score,
    p.friction_score,
    p.neutral_score,
    e.expected_direction,
    e.note
   FROM parsed p
     JOIN ccc.forecast_regression_expectations e ON e.entity_name = p.entity_name;;


COMMENT ON FUNCTION ccc.forecast_v1_1(text)
IS 'RSAL P7.3d stable wrapper: calls forecast_v1_1_core and applies confidence evidence gate. Fixed checkpoint: P7.3d_forecast_v1_1_confidence_gate_stable.';

COMMENT ON FUNCTION ccc.forecast_v1_1_core(text)
IS 'RSAL P7.3c core forecast function: route-specific semantic alignment. Do not edit directly without snapshot.';

COMMENT ON FUNCTION ccc.forecast_confidence_gate_v1(double precision, double precision, double precision)
IS 'RSAL P7.3d confidence gate: direction balance multiplied by evidence strength.';
