#!/usr/bin/env python3
import os
import hashlib
from pathlib import Path

import psycopg2


DB = {
    "host": "localhost",
    "port": 5432,
    "dbname": "postgres",
    "user": "postgres",
    "password": os.environ.get("LOCAL_PG_PASSWORD", ""),
}

CHECKPOINT = "P7.3d_forecast_v1_1_confidence_gate_stable"

OUT = Path("backups/p7_checkpoint/p7_3d_checkpoint_full.sql")


def q(cur, sql, params=None):
    cur.execute(sql, params or ())
    return cur.fetchall()


def one(cur, sql, params=None):
    cur.execute(sql, params or ())
    row = cur.fetchone()
    return row[0] if row else None


def write_insert(cur, f, table, cols, rows, conflict_sql):
    if not rows:
        return

    col_sql = ", ".join(cols)
    placeholder = ", ".join(["%s"] * len(cols))

    for row in rows:
        values_sql = cur.mogrify(f"({placeholder})", row).decode("utf-8")
        f.write(
            f"INSERT INTO {table} ({col_sql}) VALUES {values_sql}\n"
            f"{conflict_sql};\n\n"
        )


def main():
    OUT.parent.mkdir(parents=True, exist_ok=True)

    conn = psycopg2.connect(**DB)
    conn.autocommit = True
    cur = conn.cursor()

    with OUT.open("w", encoding="utf-8") as f:
        f.write("-- RSAL P7.3d checkpoint full backup\n")
        f.write(f"-- checkpoint: {CHECKPOINT}\n")
        f.write("-- generated by scripts/export_p7_checkpoint.py\n\n")

        f.write("CREATE SCHEMA IF NOT EXISTS ccc;\n\n")

        # 1. Functions
        f.write("-- ============================================================\n")
        f.write("-- Functions\n")
        f.write("-- ============================================================\n\n")

        function_sigs = [
            "ccc.forecast_confidence_gate_v1(double precision,double precision,double precision)",
            "ccc.forecast_v1_1_core(text)",
            "ccc.forecast_v1_1(text)",
        ]

        for sig in function_sigs:
            definition = one(cur, "SELECT pg_get_functiondef(%s::regprocedure)", (sig,))
            if definition is None:
                raise RuntimeError(f"Function not found: {sig}")

            f.write(f"-- Function: {sig}\n")
            f.write(definition)
            if not definition.rstrip().endswith(";"):
                f.write(";")
            f.write("\n\n")

        # 2. Tables
        f.write("-- ============================================================\n")
        f.write("-- Checkpoint tables\n")
        f.write("-- ============================================================\n\n")

        f.write("""
CREATE TABLE IF NOT EXISTS ccc.rsal_checkpoints (
  id bigserial PRIMARY KEY,
  checkpoint_label text UNIQUE NOT NULL,
  module text NOT NULL,
  note text,
  created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ccc.function_snapshots (
  id bigserial PRIMARY KEY,
  checkpoint_label text NOT NULL,
  function_signature text NOT NULL,
  function_definition text NOT NULL,
  definition_hash text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  UNIQUE (checkpoint_label, function_signature)
);

CREATE TABLE IF NOT EXISTS ccc.forecast_regression_expectations (
  entity_name text PRIMARY KEY,
  expected_route_profile text NOT NULL,
  expected_option_a text NOT NULL,
  expected_option_b text NOT NULL,
  min_confidence numeric NOT NULL,
  max_confidence numeric NOT NULL,
  min_total_force numeric NOT NULL,
  max_total_force numeric NOT NULL,
  expected_direction text NOT NULL,
  note text,
  updated_at timestamp with time zone DEFAULT now()
);

""")

        # 3. Data: rsal_checkpoints
        rows = q(
            cur,
            """
            SELECT checkpoint_label, module, note, created_at
            FROM ccc.rsal_checkpoints
            WHERE checkpoint_label = %s
            """,
            (CHECKPOINT,),
        )

        write_insert(
            cur,
            f,
            "ccc.rsal_checkpoints",
            ["checkpoint_label", "module", "note", "created_at"],
            rows,
            """
ON CONFLICT (checkpoint_label) DO UPDATE SET
  module = EXCLUDED.module,
  note = EXCLUDED.note,
  created_at = EXCLUDED.created_at
""".strip(),
        )

        # 4. Data: function_snapshots
        rows = q(
            cur,
            """
            SELECT checkpoint_label, function_signature, function_definition, definition_hash, created_at
            FROM ccc.function_snapshots
            WHERE checkpoint_label = %s
            ORDER BY function_signature
            """,
            (CHECKPOINT,),
        )

        write_insert(
            cur,
            f,
            "ccc.function_snapshots",
            ["checkpoint_label", "function_signature", "function_definition", "definition_hash", "created_at"],
            rows,
            """
ON CONFLICT (checkpoint_label, function_signature) DO UPDATE SET
  function_definition = EXCLUDED.function_definition,
  definition_hash = EXCLUDED.definition_hash,
  created_at = EXCLUDED.created_at
""".strip(),
        )

        # 5. Data: forecast_regression_expectations
        rows = q(
            cur,
            """
            SELECT
              entity_name,
              expected_route_profile,
              expected_option_a,
              expected_option_b,
              min_confidence,
              max_confidence,
              min_total_force,
              max_total_force,
              expected_direction,
              note,
              updated_at
            FROM ccc.forecast_regression_expectations
            WHERE entity_name IN ('习近平','中共','美联储','WEF','特朗普')
            ORDER BY entity_name
            """,
        )

        write_insert(
            cur,
            f,
            "ccc.forecast_regression_expectations",
            [
                "entity_name",
                "expected_route_profile",
                "expected_option_a",
                "expected_option_b",
                "min_confidence",
                "max_confidence",
                "min_total_force",
                "max_total_force",
                "expected_direction",
                "note",
                "updated_at",
            ],
            rows,
            """
ON CONFLICT (entity_name) DO UPDATE SET
  expected_route_profile = EXCLUDED.expected_route_profile,
  expected_option_a = EXCLUDED.expected_option_a,
  expected_option_b = EXCLUDED.expected_option_b,
  min_confidence = EXCLUDED.min_confidence,
  max_confidence = EXCLUDED.max_confidence,
  min_total_force = EXCLUDED.min_total_force,
  max_total_force = EXCLUDED.max_total_force,
  expected_direction = EXCLUDED.expected_direction,
  note = EXCLUDED.note,
  updated_at = EXCLUDED.updated_at
""".strip(),
        )

        # 6. View
        f.write("-- ============================================================\n")
        f.write("-- Regression view\n")
        f.write("-- ============================================================\n\n")

        view_def = one(
            cur,
            "SELECT pg_get_viewdef('ccc.forecast_v1_1_regression'::regclass, true)"
        )

        if view_def:
            f.write("CREATE OR REPLACE VIEW ccc.forecast_v1_1_regression AS\n")
            f.write(view_def.rstrip())
            f.write(";\n\n")
        else:
            f.write("-- View ccc.forecast_v1_1_regression not found.\n\n")

        # 7. Comments
        f.write("""
COMMENT ON FUNCTION ccc.forecast_v1_1(text)
IS 'RSAL P7.3d stable wrapper: calls forecast_v1_1_core and applies confidence evidence gate. Fixed checkpoint: P7.3d_forecast_v1_1_confidence_gate_stable.';

COMMENT ON FUNCTION ccc.forecast_v1_1_core(text)
IS 'RSAL P7.3c core forecast function: route-specific semantic alignment. Do not edit directly without snapshot.';

COMMENT ON FUNCTION ccc.forecast_confidence_gate_v1(double precision, double precision, double precision)
IS 'RSAL P7.3d confidence gate: direction balance multiplied by evidence strength.';
""")

    digest = hashlib.md5(OUT.read_bytes()).hexdigest()
    print(f"✅ Exported: {OUT}")
    print(f"✅ MD5: {digest}")


if __name__ == "__main__":
    main()
